### ISSUE TITLE
Examples on distributed server environment(i.e. scaling-out)

### ISSUE THREAD

**Issue by taey16** [twitter/torch-distlearn#11]
Please, give me comments or example codes to use this torch-distlearn in distributed servers.(i.e. scaling-out)

**Comment by zakattacktwitter** [comment]
Hi,

There are example scripts in the examples directory. Folks have used these on their own clusters as well as AWS. No cluster is the same, so you'll need to do some work depending on what type of cluster you want to use.

Thanks,
Zak
