### ISSUE TITLE
Do you have any number for the expected speed-up between one GPU and multiple GPUs?

### ISSUE THREAD

**Issue by chienlinhuang1116** [twitter/torch-distlearn#12]
Hi, Do you have any number for the expected speed-up between one GPU and multiple GPUs? Results of MNIST and Cifar10 dataset are shown as followings respectively. Are they correct?

Thank you,
Chien-Lin

```
Input: 1024(=1x32x32) dimensions; 60,000 images
Output: 10 dimensions, a sparse vector
Network: 2 Convolution NNs + 1 linear NN
GPU1 total time: 138.024 sec, Batch size: per node = 1, total = 1
GPU2 total time: 108.990 sec, Batch size: per node = 1, total = 2
GPU4 total time:  89.639 sec, Batch size: per node = 1, total = 4
GPU6 total time:  82.023 sec, Batch size: per node = 1, total = 6

Input: 3x32x32 dimensions; 50,000 images
Output: 10 dimensions, a sparse vector
Network: 4 Convolution NNs + 1 linear NN
GPU1 total time: 128.232 sec, Batch size: per node = 32, total = 32
GPU2 total time: 117.435 sec, Batch size: per node = 16, total = 32
GPU4 total time:  98.507 sec, Batch size: per node =  8, total = 32
```

**Comment by zakattacktwitter** [comment]
Seems like reasonable speed ups. Remember, MNIST and CIFAR are tiny networks (by today's standards) and do not benefit much from distributed learning. The only reason I included them was because they are in the public domain and well known.

**Comment by chienlinhuang1116** [comment]
Thank you Zak. You did really amazing works. I had results on comparing the raw computational efficiency of two toolkits “nn.DataParallelTable” and “torch-distlearn” using simulated data. 

Results of nn.DataParallelTable (the bigger number is better):
![image](https://cloud.githubusercontent.com/assets/16109566/13995007/987ec12e-f0e4-11e5-9379-9d87e4693f3d.png)


Results of torch-distlearn (the bigger number is better):
![image](https://cloud.githubusercontent.com/assets/16109566/13995001/91df4e7e-f0e4-11e5-8272-63c3690ce512.png)
