### ISSUE TITLE
Problems with Using CPU as a node

### ISSUE THREAD

**Issue by shanlior** [twitter/torch-distlearn#13]
Hello I'm currently using the current settings:
I have a 32-core server with 2 titan-x GPU's.

I want to use this package in order to research and implement asynchronous algorithms for deep learning. I want to use the system with more than 2 workers. I thought of using 2 nodes for the GPU's, and using more nodes which are running on CPU. 
However, even when I use 1 CPU node, it uses all of the free cores, which causes the PC performance to drop significantly. Using more than 1 CPU node, just causes the the cores to be split into few nodes. I wondered if you experienced that problem?

1) Can I decide how many cores are active instead of just deciding the number of CPU nodes? If so, can I leave some of the cores free for memory transfers? Do you think it will fix the drop in performance?
2) Did anyone try using GPU's and CPU cores all together?
3) This package is based upon the torch-ipc package. I've got more GPU's in other PC's and I wondered if I can use them using torch-distlearn. Can I tweak it so It won't just be active locally?
I've noticed that the implementation uses LocalhostTree. Can it easily be changed?

Thanks in advance,
It will be of a tremendous help,
Lior

**Comment by zakattacktwitter** [comment]
Hi,

That's a lot of questions.

I am sure its possible but I haven't heard of anyone using CPU and GPU nodes to work on the same model. The code paths for CPU vs GPU are quite different so we usually pick one or the other.

When running a model on a CPU Torch uses OpenMP and BLAS (or Accelerate on the Mac) to do computations. On Linux you can reduce the number of threads used by OpenMP by setting the OMP_NUM_THREADS environment variable.

> OMP_NUM_THREADS=1 th myscript.lua

 LocalhostTree is just one of many types of tree initializers, look around in the source.

**Comment by shanlior** [comment]
Hi,

I'm only trying to do it in order to be able to use as much workers as I can, running asynchronously. 

I'll try it with OMP_NUM_THREADS.

I've already looked at the source and tried to use other types of tree initializers.

I'm trying to run it over two PC's. Let's call the first one the server, and the other one the client
The server's IP is lets say: 11.11.11.11

On the server I run:
#!/usr/bin/env bash
th remote.lua --numNodes 2 --base 2 --cuda --gpu 1 --nodeIndex 1 --batchSize 256 --host 11.11.11.11 --port 80105
wait

and on the client:
#!/usr/bin/env bash
th remote.lua --numNodes 2 --base 2 --cuda --gpu1 --nodeIndex 2 --batchSize 256 --host 11.11.11.11 --port 80105
wait

But it doesn't work.

While I only run the server script it waits, but when I run the other script over the client it says the following error over the client:

/home/lior/torch/install/bin/luajit: /home/lior/torch/install/share/lua/5.1/ipc/Tree.lua:79: ERROR: (/tmp/luarocks_ipc-scm-1-6030/torch-ipc/src/cliser.c, 206): (99, Cannot assign requested address)

and on the server:

ERROR: (/tmp/luarocks_ipc-scm-1-647/torch-ipc/src/cliser.c, 543): (104, Connection reset by peer)

**Comment by zakattacktwitter** [comment]
Can you run a web server on one machine and connect to it with the other?
Try using the same ip and port you listed below.

**Comment by zakattacktwitter** [comment]
Or more clearly, have you verified these machines can talk to each other on
the ip and port you listed?

**Comment by shanlior** [comment]
I'll look into it. I'm not sure how to check it.

I can use a vnc server or ssh over the two workstations, but i'm not sure how to open the server and connect to it. I'll try and google it.


Thanks for now,

Lior

**Comment by shanlior** [comment]
I figured it out!

On the client you must I've added:

**th remote.lua --numNodes 2 --base 2 --cuda --gpu1 --nodeIndex 2 --batchSize 256 --host 11.11.11.11 --localIP [localIP] --port 80105**

and I've changed:
**local tree = Tree(opt.nodeIndex, opt.numNodes, opt.base, server, client, opt.host, opt.port + opt.nodeIndex)**
to
**local tree = Tree(opt.nodeIndex, opt.numNodes, opt.base, server, client, opt.localIP, opt.port + opt.nodeIndex)**

**Comment by zakattacktwitter** [comment]
Glad you got it working.
