### ISSUE TITLE
Does this work on AWS?

### ISSUE THREAD

**Issue by willfrey** [twitter/torch-distlearn#5]
I tried to get distlearn working between two GPUs on an AWS node but received this error:

INFO: torch-ipc: CUDA IPC not possible between GPU2 and GPU3
INFO: torch-ipc: CUDA IPC not possible between GPU3 and GPU2

The AWS GPUs are virtual — does this preclude them from communicating?

Thanks!

**Comment by zakattacktwitter** [comment]
Hi,

Yeah, AWS does not support GPU to GPU communication directly due to
limitations in the Citrix virtualization layer. That message is just a
warning letting you know that IPC detected it and is using a slower path.
The GPUs will still be able to participate in the distributed learning, but
will be forced to communicate over a slower path (through main memory). It
all works, just a bit slower.

Hope this makes sense,
Zak

**Comment by willfrey** [comment]
Makes sense!

Thanks.

On Fri, Feb 12, 2016 at 12:26 PM, zakattacktwitter <notifications@github.com
> wrote:

> Hi,
>
> Yeah, AWS does not support GPU to GPU communication directly due to
> limitations in the Citrix virtualization layer. That message is just a
> warning letting you know that IPC detected it and is using a slower path.
> The GPUs will still be able to participate in the distributed learning, but
> will be forced to communicate over a slower path (through main memory). It
> all works, just a bit slower.
>
> Hope this makes sense,
> Zak
>
>
>
> On Fri, Feb 12, 2016 at 9:18 AM, willfrey <notifications@github.com>
> wrote:
>
> > I tried to get distlearn working between two GPUs on an AWS node but
> > received this error:
> >
> > INFO: torch-ipc: CUDA IPC not possible between GPU2 and GPU3
> > INFO: torch-ipc: CUDA IPC not possible between GPU3 and GPU2
> >
> > The AWS GPUs are virtual — does this preclude them from communicating?
> >
> > Thanks!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/twitter/torch-distlearn/issues/5>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/torch-distlearn/issues/5#issuecomment-183420834>
> .
>



-- 
Will Frey
Software Engineer |* Digital Reasoning*
Cell: 703.915.8592 <615.838.0457>
901 N Stuart St., Suite 902
Arlington, VA 22203
www.digitalreasoning.com
