### ISSUE TITLE
"CUDA IPC not possible between GPUs" & "CUDA IPC enabled between GPUs"

### ISSUE THREAD

**Issue by chienlinhuang1116** [twitter/torch-distlearn#8]
Hi, I tried to get distlearn working between multiple GPUs on my local machine (consists of 32cpu and 8gpu-Tesla-K80) but received the following messages. It seems to automatically enable CUDA IPC between GPUs, but I got the pretty low accuracy and very long time for computing each Epoch. Do you have any suggestion?

Thank you.

Chien-Lin

------------------------ Input
th mnist2.lua --numNodes 8 --nodeIndex 1 --cuda --gpu 1 &
th mnist2.lua --numNodes 8 --nodeIndex 2 --cuda --gpu 2 &
th mnist2.lua --numNodes 8 --nodeIndex 3 --cuda --gpu 3 &
th mnist2.lua --numNodes 8 --nodeIndex 4 --cuda --gpu 4 &
th mnist2.lua --numNodes 8 --nodeIndex 5 --cuda --gpu 5 &
th mnist2.lua --numNodes 8 --nodeIndex 6 --cuda --gpu 6 &
th mnist2.lua --numNodes 8 --nodeIndex 7 --cuda --gpu 7 &
th mnist2.lua --numNodes 8 --nodeIndex 8 --cuda --gpu 8 &
------------------------ Output
INFO: torch-ipc: CUDA IPC not possible between GPU2 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU2
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU3
INFO: torch-ipc: CUDA IPC not possible between GPU3 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU4 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU4
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU6
INFO: torch-ipc: CUDA IPC not possible between GPU6 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU7
INFO: torch-ipc: CUDA IPC not possible between GPU7 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU5
INFO: torch-ipc: CUDA IPC not possible between GPU5 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU1 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU0 and GPU1
INFO: torch-ipc: CUDA IPC enabled between GPU4 and GPU5
INFO: torch-ipc: CUDA IPC enabled between GPU5 and GPU4
INFO: torch-ipc: CUDA IPC enabled between GPU7 and GPU6
INFO: torch-ipc: CUDA IPC enabled between GPU6 and GPU7
INFO: torch-ipc: CUDA IPC enabled between GPU2 and GPU3
INFO: torch-ipc: CUDA IPC enabled between GPU3 and GPU2
INFO: torch-ipc: CUDA IPC enabled between GPU6 and GPU4
INFO: torch-ipc: CUDA IPC enabled between GPU4 and GPU6

**Comment by zakattacktwitter** [comment]
Glad you got it working!

You should see the same exact results when training MNIST on a single GPU versus distributing the training across 8 GPUs, as long as every other parameter remains constant. Have you verified how the same training parameters on a single GPU behave?

Hope this helps,
Zak

**Comment by chienlinhuang1116** [comment]
Hi, I did some experiments shown as followings. It is correct on the AWS Ubuntu instance, but I got strange results from my GPU machine:

**on the AWS Ubuntu instance (32cpu & 4gpu-GRID-K520):**
------------------------------------- multiple jobs (nodes) -------------------------------------
1job without gpu         global correct: 97.7%           total time: 6809.4 sec
4job without gpu         global correct: 97.5%           total time: 5260.1 sec
------------------------------------- multiple gpus -------------------------------------
1job with 1gpu              global correct: 98.5%          total time: 135.9 sec
2job with 2gpu              global correct: 98.1%          total time: 112.9 sec
4job with 4gpu              global correct: 97.5%          total time:   89.3 sec

**on my GPU machine (32cpu & 8gpu-Tesla-K80):**
------------------------------------- multiple gpus -------------------------------------
1job with 1gpu              global correct: 97.2%          total time: 135.7 sec
2job with 2gpu              global correct: 10.4%          total time: ~20790 sec
INFO: torch-ipc: CUDA IPC enabled between GPU1 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU0 and GPU1
4job with 4gpu              global correct: 10.2%          total time: ~10410 sec
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU3
INFO: torch-ipc: CUDA IPC not possible between GPU3 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU2
INFO: torch-ipc: CUDA IPC not possible between GPU2 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU1 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU0 and GPU1
INFO: torch-ipc: CUDA IPC enabled between GPU3 and GPU2
INFO: torch-ipc: CUDA IPC enabled between GPU2 and GPU3
8job with 8gpu              global correct: 10.3%          total time: ~10455 sec
INFO: torch-ipc: CUDA IPC not possible between GPU2 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU2
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU3
INFO: torch-ipc: CUDA IPC not possible between GPU3 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU4 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU4
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU6
INFO: torch-ipc: CUDA IPC not possible between GPU6 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU7
INFO: torch-ipc: CUDA IPC not possible between GPU7 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU5
INFO: torch-ipc: CUDA IPC not possible between GPU5 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU1 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU0 and GPU1
INFO: torch-ipc: CUDA IPC enabled between GPU4 and GPU5
INFO: torch-ipc: CUDA IPC enabled between GPU5 and GPU4
INFO: torch-ipc: CUDA IPC enabled between GPU7 and GPU6
INFO: torch-ipc: CUDA IPC enabled between GPU6 and GPU7
INFO: torch-ipc: CUDA IPC enabled between GPU2 and GPU3
INFO: torch-ipc: CUDA IPC enabled between GPU3 and GPU2
INFO: torch-ipc: CUDA IPC enabled between GPU6 and GPU4
INFO: torch-ipc: CUDA IPC enabled between GPU4 and GPU6

**Comment by chienlinhuang1116** [comment]
Thank you Zak. This problem can be solved by disabling ACS.

There is a discussion about "Multi-GPU Peer to Peer access failing on Tesla K80" [https://devtalk.nvidia.com/default/topic/883054/cuda-programming-and-performance/multi-gpu-peer-to-peer-access-failing-on-tesla-k80](https://devtalk.nvidia.com/default/topic/883054/cuda-programming-and-performance/multi-gpu-peer-to-peer-access-failing-on-tesla-k80).
